### ISSUE TITLE
parser fails to compile

### ISSUE THREAD

**Issue by holgerbrandl** [mpicbg-scicomp/tissue_miner#13]
When using
```
Distributor ID:	Ubuntu
Description:	Ubuntu 15.10
Release:	15.10
Codename:	wily
```
the parser fails to compile with the follwing error
```
brandl@brandl-virtual-machine:~/my_tm/parser$ make
g++ -O3 -g -IFramework -IParser -I/usr/include/qt4 -DPROGRAMNAME=\"imageParser\" -DVERSION=\"150820-01\" -c -o Framework/QtImage.o Framework/QtImage.cpp
Framework/QtImage.cpp:1:21: fatal error: Qt/QtCore: No such file or directory
```

I've checked and at least the defined dependencies `qt4-dev-tools libqt4-core` are installed as defined in `install_dependencies.sh`

Did you have the same problem with 14.10 and 15.04?

**Comment by etournay** [comment]
Yes, I do confirm. This is due to the --no-install-recommends option used in apt-get. This idea of this option is to avoid installing the documentation including about 100MB of qt4-doc, which is not necessary and long to download. However the parser doesn't compile anymore. Interestingly I get the exact same message as on MacOS when installing QT4 from brew = some packages might be missing.
To fix this issue in Ubuntu, first remove the --no-install-recommends option for qt4 installation. And clean up before reinstalling:

```
sudo apt-get remove qt4-dev-tools libqt4-core
sudo apt-get purge qt4-dev-tools libqt4-core
sudo apt-get clean
```
Re-run install_tm.sh (without the R setup) and the parser compiles fine on both Ubuntu's
