### ISSUE TITLE
More generic ROI tracking needed

### ISSUE THREAD

**Issue by holgerbrandl** [mpicbg-scicomp/tissue_miner#8]
I checked the definition of the void cell. The parser always discard the pseudo cells that touch the image border and replace them by the void cell.
Therefore the void cell (cell_id == 10000) always defines the image border (see movies on dropbox)

I didn't remember this neither, but that is a good news: all cells in contact with cell_id == 10000 are margin cells, with no exception.
To make the back tracking more generic, this idea would be to discard all cell lineages that touch the void cell at least once in the movie.

**Comment by holgerbrandl** [comment]
The existing algo is "pupal wing specific" because we knew the cell influx and we decided to do it on the first frame because it was fine for the pupal wing.  It makes sense for the pupal wing: this allowed us to remove more cells in the bottom (posterior compartment) than in the top, as desired.

We could simply expose a “remove-margin-lineages-in-frame” option:
* if not set (default?), we don’t peel
* if set to a specific frame we do as before but just using the given frame instead of 1
* if set to "all", all lineages in a 2-cell range from the margin are removed.

We should also rename LastFrameRoiBT.R to something more descriptive.

Given the definition of the void cell at the image border from above, this method should work for the image border without further modifications.

**Comment by etournay** [comment]
Can the peeling be a parameter ?
Depending on the segmentation mask and its segmentation quality near the margin, we may vary the number of cell rows to peel off.

Here is what I would expect:
* by default, remove cell lineages that touch the void cell (image boder) in any frames of the movie, optionally select a single frame to filter out lineages (to reproduce our ROI in the pupal wing). Removing the entire lineage is already pretty drastic.
* peeling concerns cells that are not in contact to the void cell but still too close to the border to be well segmented: default could be 1 more cell row to peel off.

In total, this would discard (at least) two cell rows from the void cell, by default, depending on the lineage size.
Would that fit in the current scheme ?

Best,
Rapha


----- Mail original -----
De: "Holger Brandl" <notifications@github.com>
À: "mpicbg-scicomp/tissue_miner" <tissue_miner@noreply.github.com>
Envoyé: Mardi 26 Janvier 2016 10:44:28
Objet: Re: [tissue_miner] More generic ROI tracking needed (#8)

The existing algo is "pupal wing specific" because we knew the cell influx and we decided to do it on the first frame because it was fine for the pupal wing.  It makes sense for the pupal wing: this allowed us to remove more cells in the bottom (posterior compartment) than in the top, as desired.

We could simply expose a “remove-margin-lineages-in-frame” option:
* if not set (default?), we don’t peel
* if set to a specific frame we do as before but just using the given frame instead of 1
* if set to "all", all lineages in a 2-cell range from the margin are removed.

We should also rename LastFrameRoiBT.R to something more descriptive.

Given the definition of the void cell at the image border from above, this method should work for the image border without further modifications.

---

**Comment by etournay** [comment]
Hi Holger,
Just to keep you posted, I'll take care of it. The hole filling works well anyway (as long as cell are not touching the void cell), I won't touch it. I created a new script called UserRoiTracking.R. Under heavy testing... Works perfectly so far and very generic.

This script could potentially replace LastFrameRoiBT.R
Best,
Raphael

**Comment by etournay** [comment]
Tests were very good. The border cell-lineage definition is robust against poor segmentation quality near the margin. I didn't include the hull calculation that stays in the old LastFrameRoiBT.R. I switched to this new script in the workflow.
